### ISSUE TITLE
Different results when switching entries

### ISSUE THREAD

**Issue by yhuard** [mapbox/pixelmatch#10]
Hello,

First I'd like to thank you for this nice library.

Then I'd like to report a strange behavior: `pixelmatch test.png test2.png output.png 0 true` and `pixelmatch test2.png test.png output.png 0 true` don't provide the same result. In my test case, test.png is the base image (greyscale) and test2.png is the same image with some white painting upon it. This painting isn't detected during the second test whereas it is during the first one. 

Is it the expected behavior when working with greyscale pictures or a bug in the library?

**Comment by mourner** [comment]
Hmm, this is weird. Can you provide the sample images to reproduce this?

**Comment by yhuard** [comment]
Ok, I've found how to reproduce it. Here's the full procedure:
1. first I take a screenshot during a test using [nightmarejs](http://www.nightmarejs.org/), I name it "test.png"
2. I copy it to "test2.png". If I run the test with pixelmatch, they match (fortunately)
3. then I edit test2.png with Photoshop, add some crap and save it. Now it gets funny: if I run `pixelmatch test.png test2.png output.png 0 true`, I get a `different pixels: 0` but when I run `pixelmatch test2.png test.png output.png 0 true`, the result is `different pixels: 66813`. *This is the weird part...*
4. Finally, if I load "test.png" in Photoshop and save it (without editing it), the result is good in both ways: pixelmatch can find the 66813 different pixels

So I guess that Photoshop added or removed some metadata from the PNG fille but still, it's weird that `pixelmatch test.png test2.png` and `pixelmatch test2.png test.png` offer two different results.

Here are the two pictures:
![test](https://cloud.githubusercontent.com/assets/3524389/11448073/9cd8d992-9551-11e5-84da-c5ef1201cd16.png)
![test2](https://cloud.githubusercontent.com/assets/3524389/11448074/9cd8d19a-9551-11e5-9344-1ba14d31568b.png)

If you manage to resolve this issue, I'd be glad to use this library and talk about it

**Comment by mourner** [comment]
Hmm, I can't reproduce this — here's the output with both commands:

```bash
~/projects/pixelmatch master* → ./bin/pixelmatch tmp/bug.png tmp/bug2.png output.png 0 true
match: 17.008ms
different pixels: 66813
error: 35.54%
~/projects/pixelmatch master* → ./bin/pixelmatch tmp/bug2.png tmp/bug.png output.png 0 true
match: 14.225ms
different pixels: 66813
error: 35.54%
```

![output](https://cloud.githubusercontent.com/assets/25395/11470518/09e24c00-9767-11e5-998a-484995b501f4.png)

What your OS? Do you use the last released pixelmatch version from NPM, or the master one?

**Comment by mourner** [comment]
I have a feeling this has something to do with the command line and the way it parses arguments, not the library itself...

**Comment by yhuard** [comment]
I use Mac OS X and the latest version from npm (`"pixelmatch": "^4.0.0"`), I'll try it again

**Comment by mourner** [comment]
@yhuard could it be that nightmarejs inserts some invalid metadata into the images which both Photoshop and GitHub CDN strip away, which fixes the issue? Then this is probably something I can't fix on the pixelmatch side. Let's reopen if it turns out not to be the case.

**Comment by yhuard** [comment]
Yup, I still get this strange behaviour as soon as I edit one of the 2 pictures with Photoshop so there's something wrong somewhere in the metadata causing some mess.

The weirdest thing is that switching the order of parameters changes the results... I will investigate it and come back if I find a solution.

In the absolute it's not a real issue for me as I don't expect the user to edit the picture by himself (pictures are simple screenshots taken at different times to check for visual regression). 

Let's keep this issue closed

**Comment by yhuard** [comment]
Got it!

In bin/pixelmatch, you call the function `var diffs = match(img1.data, this.data, ...` when it should be `var diffs = match(img1.data, img2.data, ...` because we can't be sure that `this` refers to `img2`.

That's why the diff found no result, because it was trying to diff the same image.

**Comment by yhuard** [comment]
PR created #12
