### ISSUE TITLE
Image Size doesn't match

### ISSUE THREAD

**Issue by MrBiscuit** [mapbox/pixelmatch#100]
I get countless `Image data size does not match width/height` and `Image sizes do not match` error even calling the function as simple as
`pixelmatch(new Uint8Array(2),new Uint8Array(2),null)` assigning width height or not

Even passing in the same image for both img1 and img2 arguments, will forever raise this `Image data size does not match width/height` error no matter what.

Please help, I never get this to work

**Comment by MrBiscuit** [comment]
<img width="843" alt="Screen Shot 2021-11-03 at 12 04 34 PM" src="https://user-images.githubusercontent.com/13072026/140008684-9a2941c6-03e2-4a8e-95dc-a1b9b849ab84.png">
<img width="1436" alt="Screen Shot 2021-11-03 at 12 06 37 PM" src="https://user-images.githubusercontent.com/13072026/140008768-cbcd1312-6982-4f88-9da3-602fb60fb8c9.png">

**Comment by mourner** [comment]
The input for image data assumes 4 values (R, G, B, A) for each pixel. This is way the library has this condition on input:

https://github.com/mapbox/pixelmatch/blob/b9261a447515f5aff37a15cfab9f4a491868f720/index.js#L23

Make sure your input images data lenth equals `width * height * 4`.

**Comment by MrBiscuit** [comment]
I've tried all numbers, including `width * height * 4` and all of them throw 'Image data size does not match width/height.'
