### ISSUE TITLE
Optimized Image's Unit8Array data length is always smaller than w*h*4

### ISSUE THREAD

**Issue by MrBiscuit** [mapbox/pixelmatch#102]
**I did read everything in the readme and all the past issues (open+closed) before raising the issue, so please don't judge me by the cover 🙏🏻** 
For a 100x100 **optimized** PNG image, The more complex it is, the closer it gets to 40000 length, but mostly it won't come close, see examples provided below(all of them are 100x100):

![cc](https://user-images.githubusercontent.com/13072026/140035401-d6ec851b-2fbc-45fe-8c2d-5cb4e19938ac.png)
^ This one has a length of 31818

![23](https://user-images.githubusercontent.com/13072026/140036512-d4edd53e-fe47-416b-b6fa-f2df806e9b5f.png)
^ This one has a length of 20205

![Rectangle](https://user-images.githubusercontent.com/13072026/140034155-bb3419bc-05ad-42d2-9637-a5687dd3e652.png) 
^This one has a length of 10377

![img1](https://user-images.githubusercontent.com/13072026/140034922-298f0a8c-34ce-4d50-8008-737a2a7dd0d9.png)
^ This one has a length of 492

![Rectangle 4](https://user-images.githubusercontent.com/13072026/140034307-43a31b69-63e7-4222-8760-adfdcb591769.png)
^ This one has a length of 345

**Comment by mourner** [comment]
Please read the readme examples carefully and stop spamming new issues. You're passing encoded PNG buffer as input, whereas you need to decode the image first, and pass the pixel data.
