### ISSUE TITLE
Get infos when run

### ISSUE THREAD

**Issue by jehon** [mapbox/pixelmatch#103]
Is it possible to generate the diff AND to get a structured info?

Style: { diff: 0.15 } or something like that...

Objective: to compare and to know if the comparison lead to a lot of change or not...

PS: no idea what the result should be, be an information in form of % would be nice (I mean independent of the size of the picture)

**Comment by mourner** [comment]
`pixelmatch` returns the number of different pixels after comparison. If you need %, just do `numDiffPixels / (width * height)`.

**Comment by jehon** [comment]
Could be documented :-)
