### ISSUE TITLE
Publish the latest changes to npm?

### ISSUE THREAD

**Issue by styfle** [mapbox/pixelmatch#108]
It looks like the latest version of pixelmatch was published 2 years ago https://www.npmjs.com/package/pixelmatch

However, there are some changes made to this repo 8 months ago.

Could someone with the correct permission publish these changes to npm? 

Perhaps @mourner. Thanks!

**Comment by mourner** [comment]
Why do you need a new version? As you can see in the commit log, there were no actual code changes in the library, only development updates. It's working perfectly as it is.

**Comment by styfle** [comment]
The dependencies were bumped to PNGJS 6.x

**Comment by styfle** [comment]
You can see playwright had a workaround for this outdated dependency here https://github.com/microsoft/playwright/blob/7f513360681d2517caa24d266def9b3a7be4f469/packages/playwright-core/src/utils/comparators.ts#L23-L24

**Comment by mourner** [comment]
Thanks for the details and sorry for the delay! Released as v5.3.0.
