### ISSUE TITLE
pixelmatch 5 fails in browser script tags without a `module` object

### ISSUE THREAD

**Issue by ggorlen** [mapbox/pixelmatch#110]
It's possible to use pixelmatch 5 in a `<script>` tag using the following pattern:

```html
<script>module = {};</script>
<script src="https://cdn.jsdelivr.net/npm/pixelmatch@5.2.1/index.min.js"></script>
```

Older versions of pixelmatch (<= 4) don't attach to `module`. It adds a few bytes, but changing `module.exports = pixelmatch;` to `module && (module.exports = pixelmatch);` would make it a bit more client-friendly for those who want to use pixelmatch outside a build.

**Comment by mourner** [comment]
Please use the browser bundle in browser environments instead of using CommonJS with hacks: https://bundle.run/pixelmatch@5.2.0
