### ISSUE TITLE
Image data: Uint8Array, Uint8ClampedArray or Buffer expected.

### ISSUE THREAD

**Issue by IamMille** [mapbox/pixelmatch#116]
In the Node.js example, it seems like the `const diff = new PNG({width, height});` returns a stream, hence the error.

**Comment by mourner** [comment]
That stream also has a `data` property (per `pngjs` docs), so the example works as expected.

```js
pixelmatch(img1.data, img2.data, diff.data, width, height, {threshold: 0.1});
```

**Comment by gsouf** [comment]
I copy pasted the example and it's also broken for me.  img1.data is null

**Comment by mourner** [comment]
@gsouf 🤷‍♂️ you could submit an issue to pngjs, but their docs are clear: https://github.com/lukeapage/pngjs#pngsyncreadbuffer

**Comment by gsouf** [comment]
@mourner sorry I just made something wrong and because I found this 3 days old issue I just assumed there was a recent bug
