### ISSUE TITLE
Comparing two pictures with different text returns no diff

### ISSUE THREAD

**Issue by diklaby1** [mapbox/pixelmatch#117]
I'm trying to compare two pictures of a dialog with different titles, but pixelmatch return diff = 0.
Am I missing anything? I've tried different values of threshold
![screenshot](https://user-images.githubusercontent.com/110771447/183291102-7265a5bd-a164-49ce-b3da-9cf7d146237e.png)
![createPipelineDialog](https://user-images.githubusercontent.com/110771447/183291103-1a0c1cbf-a8ab-42fa-a4b1-3185c6caff6a.png)

**Comment by mourner** [comment]
I'm not sure how you're using pixelmatch since you didn't provide any details, but it works properly on the images above for me, producing this diff:

![diff](https://user-images.githubusercontent.com/25395/183883886-ced494b8-c42e-4f19-a87e-d6a6604e9d75.png)

**Comment by diklaby1** [comment]
Thank you for your response.
It seems that I had a bug in my code (I'm using a framework called
playwright which makes the code hard to debug)
I'm now getting the result as expected.

Thanks!
