### ISSUE TITLE
True or false for same image?

### ISSUE THREAD

**Issue by Jumbo125** [mapbox/pixelmatch#128]
Hello 
is it possible to get only true or false, if the images are the same?
i need a function to compare to pictures of a picture from digital time clock. if the pics are same, it is the same time. if the pictures are different, i know that's a different time

thank you

**Comment by mourner** [comment]
`pixelmatch(...) === 0` will return `true` if images are equal.

**Comment by Jumbo125** [comment]
Okay i will try it.

Can I include pixelmatch locally in my browser? The install tutorial shows only a online method for browser
