### ISSUE TITLE
install in browser not work

### ISSUE THREAD

**Issue by Jumbo125** [mapbox/pixelmatch#130]
Sorry to bother you again

I can't install it for my brwoser
if i embed
<script src="https://bundle.run/pixelmatch"></script> 
it didn't work. the path not exist

So i downlaod the last release and add this path
<script type="text/javascript" src="myserver/js/pixelmatch/bin/pixelmatch"></script>
i only get a error massage:

const PNG = require('pngjs').PNG;
ReferenceError: require is not defined

**Comment by Jumbo125** [comment]
works, include index.js datei local and remove the module line

**Comment by mourner** [comment]
I should update the link in the readme — the new working one is https://cdn.jsdelivr.net/npm/pixelmatch@5.3.0

**Comment by Jumbo125** [comment]
thank you
