### ISSUE TITLE
CommonJS based require throws error

### ISSUE THREAD

**Issue by p1100i** [mapbox/pixelmatch#137]
In the [README.md](https://github.com/mapbox/pixelmatch/blob/main/README.md?plain=1#L72) file, there is an example given which has a line: `const pixelmatch = require('pixelmatch');`

With the current `6.0.0` release, this throws the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module <PATH_A> from <PATH_B> not supported.
```

My node:
```
node --version
v22.3.0
```

Is this a deliberate change?

**Comment by mourner** [comment]
Yes, sorry, forgot to update the readme. See the release changes for v6 here: https://github.com/mapbox/pixelmatch/releases/tag/v6.0.0
