### ISSUE TITLE
PixelMatch leakinng Data Buffer

### ISSUE THREAD

**Issue by siddhant7781** [mapbox/pixelmatch#138]
I have this code:

 const numDiffPixels = pixelmatch(
      img1.data,
      img2.data,
      diff.data,
      width,
      height,
      { threshold: 0.1 }
    );
    
    when the code executes the whole buffer is leaking as an error message. Why is this happening any Idea? I am making sure everything is there needed to execute this function.  It throws no error message at all, only Buffer values.

**Comment by mourner** [comment]
There's no way to diagnose the issue without a reproducible test case, so I'll close.
