### ISSUE TITLE
diff stats

### ISSUE THREAD

**Issue by franck34** [mapbox/pixelmatch#18]
@mourner 

Hi Vladimir ! 

Nice code, very understandable.

Actualy, pixelmatch return the number of pixel diff.

Shall i suggest a PR with a breaking change so pixelmatch return an object like this (in a first time) ?

```
{
  numDiffPixels:XXXX
  misMatchPercentage: '20.33', // i need this ;)
  analysisTime: 9227
}
    
```

I'd like to go with same output format of compareTo() but without the getDiffImage() function from https://github.com/nikrolls/node-resemble/tree/user-configurable-largeimagethreshold

Are you ok with that ?

**Comment by mourner** [comment]
No, you can calculate percentage as `numDiffPixels / (width * height)`, and you can measure time by other means like `console.time`.

**Comment by franck34** [comment]
It's the second ticket related to diff in %, see #17

Returning only a number for pixelmatch function will frustrate you the day you want to add something else.

The licence of your code is ISC licence or openbsd. Let me fork that.
