### ISSUE TITLE
'pixelmatch' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by itsbang** [mapbox/pixelmatch#19]
Hi - I'm a newbie to node.js. I would like to use pixelmatch for my project. However, not finding appropriate usage document anywhere. I get the above error. Here's what I did -
1. Download https://github.com/mapbox/pixelmatch4.0.1
2. On command prompt, npm install pixelmatch
3. Set the environment variables -> Control Panel\System and Security\System >> Environment variables >> System Variables >> Path >>C:\Pixelmatch\pixelmatch-4.0.1\bin; >> Ok >> Ok >> Ok
4. On command prompt, C:\Pixelmatch\pixelmatch-4.0.1\bin> pixelmatch image1.png image2.png output.png 0.1 as a test command. 

I'm unable to proceed further. What I could be possibly missing? Request to respond ASAP. Thanks a ton. 

You've great day ahead.

**Comment by mourner** [comment]
Sorry, I just noticed the issue. Did you figure it out? For the command line on Windows, you would probably need to prepend `node` before the command — `node pixelmatch ...`.
