### ISSUE TITLE
Fails to detect difference

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/pixelmatch#21]
expected.png:

![image](https://cloud.githubusercontent.com/assets/98601/15379492/afe57302-1d22-11e6-8551-fcd6c7aec288.png)

actual.png:

![image](https://cloud.githubusercontent.com/assets/98601/15379494/b45d5350-1d22-11e6-8492-1a32f8fa3db0.png)

```
$ pixelmatch {expected,actual,diff}.png
match: 16ms
different pixels: 0
error: 0%
```

**Comment by jfirebaugh** [comment]
If I use a color other than pure black, it works.

**Comment by jfirebaugh** [comment]
Maybe failing for the same reasons as https://github.com/mapbox/pixelmatch/issues/13#issuecomment-183144836.

**Comment by mourner** [comment]
Yes, the reason for the bug is that the first version is alpha-blended with black before comparison.
