### ISSUE TITLE
Does not compare the whole image

### ISSUE THREAD

**Issue by AnzeVersnik** [mapbox/pixelmatch#30]
When I compare images usually lets say the bottom half of the image does not get returned/compared the top half works perfect . And I don't really know why that happens. [https://imgur.com/a/WVwNu](url)  
![mzy4q](https://user-images.githubusercontent.com/26359311/29824514-0fa6e5b2-8cd2-11e7-95ad-d7ac65e9fb9b.png)

**Comment by mourner** [comment]
Can you provide a sample test case that triggers the issue? I can't reproduce.
