### ISSUE TITLE
Use Buffer.equals as initial comparison for performance gain

### ISSUE THREAD

**Issue by bontscho** [mapbox/pixelmatch#38]
hi there,

we are currently using your lib in our pipeline for visual regression tests. to decrease our runtime significantly we added an initial `Buffer.equals` to compare if the image buffers are identical (so we don't need to compare pixel by pixel with threshold). 

our scenario: taking screenshots via puppeteer and then comparing against a reference set of images

i am happy to file a PR if this library is still maintained

thanks for your work and kind regards

**Comment by mourner** [comment]
Sure, that's a nice idea — a PR would be welcome! 

We should probably use a manual loop pre-check instead of `Buffer.equals` so that it works for Uint8Array cases too.

**Comment by dnfield** [comment]
In this case, I assume you just skip the output buffer?

**Comment by bontscho** [comment]
PR https://github.com/mapbox/pixelmatch/pull/39 is open

@dnfield i added an option to be a non breaking update

@mourner I am interested in what platforms you want to support in terms of node version, ES6 / TypeScript code update

**Comment by phawxby** [comment]
@bontscho we do the same use `jest-image-snapshot`, it now has the equivalent functionality 
https://github.com/americanexpress/jest-image-snapshot/pull/106
