### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [mapbox/pixelmatch#41]
I am processing 300 DPI gray scale image with resolution of 10800x7200 , and it consumes large memory (> 2GB) and takes long time (> 10 sec).

Is this normal behavior?

**Comment by mourner** [comment]
I think it's normal. 10800 * 7200 is really huge, Node has a hard time just decoding a PNG like that. Pixelmatch algorithm doesn't do anything special that could slow things down — you can see that in the code.
