### ISSUE TITLE
Different tolerance for color and placement

### ISSUE THREAD

**Issue by tylertrotter** [mapbox/pixelmatch#42]
I'm having a problem where my tolerance threshold needs to be set very low to pick up fairly obvious color differences but then it picks up slight differences in text placement that are causing a lot of false positives. You think it is a good idea to be able to set color threshold separately?

**Comment by mourner** [comment]
I don't think it's technically possible. Pixelmatch only compares colors, and technically there's a big difference between a white pixel and a black one (if something moved).
