### ISSUE TITLE
Any JPG demo code available?

### ISSUE THREAD

**Issue by rcfrias** [mapbox/pixelmatch#45]

**Comment by mourner** [comment]
No, but it doesn't matter for the algorithm.

**Comment by ko4ergins** [comment]
Hi mourner!

**Comment by ko4ergins** [comment]
Hi @rcfrias!
I wrote some ex.
`const fs = require('fs');
const pixelmatch = require('pixelmatch');
const PNG = require('pngjs').PNG;

const JPEG = require('jpeg-js');

const jpegData1 = fs.readFileSync('img1.jpg');
const img1 = JPEG.decode(jpegData1);

const jpegData2 = fs.readFileSync('img2.jpg');
const img2 = JPEG.decode(jpegData2);

const diff = new PNG({ width: img1.width, height: img1.height });

pixelmatch(img1.data, img2.data, diff.data, img1.width, img1.height, { threshold: 0.1 });

diff.pack().pipe(fs.createWriteStream('diff.png'));`
