### ISSUE TITLE
Add a section to the README.md for people who want the other kind of diffing?

### ISSUE THREAD

**Issue by Pomax** [mapbox/pixelmatch#47]
It is _surprisingly_ hard to find a library for the "real" kind of diffing, where two images are compared based on maximum identical _regions_, highlighting all the parts that are in both images, even if they moved (example: a webpage with 10px and 100px top padding is the same image. The only difference is 90 pixels of whitespace at the top).

It would be incredibly useful if there was a README.md bit going "if you're looking for a heavier weight image differ, have a look at [...]" (I still haven't found one that can actually do this, despite the fact it would make visual QA infinitely easier!)

**Comment by mourner** [comment]
To be honest, I'm not aware of tools that do what you describe, so I don't know what to add to the readme about it. If you have a good idea, feel free to open a PR.
