### ISSUE TITLE
Feature request: option to change diff layout orientation

### ISSUE THREAD

**Issue by toptalo** [mapbox/pixelmatch#48]
Need option to change diff image layout from horizontal to vertical.

Use case: site with horizontal scroll

Current output:
![image](https://user-images.githubusercontent.com/2378757/51669730-1fe3dc80-1fd6-11e9-9b2a-8e4ef9fe3aea.png)

Think this will be better:
![image](https://user-images.githubusercontent.com/2378757/51669908-836e0a00-1fd6-11e9-8ebc-1020e7c0045a.png)

**Comment by mourner** [comment]
Pixelmatch simply takes two identical images and produces a diff with the same dimension. It shouldn't concern itself with presentation issues like this — it should be done by downstream libraries using pixelmatch.
