### ISSUE TITLE
Antialiasing detection fails on image edges

### ISSUE THREAD

**Issue by IvanSanchez** [mapbox/pixelmatch#50]
I'm running some WebGL triangles in different environments, and was surprised to see a difference in this test with one triangle:

Firefox:
![rgb-triangle browser](https://user-images.githubusercontent.com/1125786/51938342-237bc700-240d-11e9-88a9-ceb8a2f07d1e.png)
`headless-gl`:
![rgb-triangle headless](https://user-images.githubusercontent.com/1125786/51938345-24145d80-240d-11e9-929d-d0e286fa5096.png)
diff:
![rgb-triangle diff](https://user-images.githubusercontent.com/1125786/51938360-28d91180-240d-11e9-9661-f450310f30a5.png)

Scaling up the images in GIMP reveals that the issue is the antialiasing in the triangle (presumably due to differences in the environment):

`headless-gl`:
![image](https://user-images.githubusercontent.com/1125786/51938516-92592000-240d-11e9-8b31-55791b64e9eb.png)
Firefox:
![image](https://user-images.githubusercontent.com/1125786/51938548-ab61d100-240d-11e9-82db-4aa06f5a0365.png)

I've manually checked the value of the alpha channels in the pixels of the diagonal, and it's the same in all: 39.5%. 

I've noticed that the antialias-detection algorithm clamps a 3x3 pixel bounding box along the edges, so I *assume* that the pixels that show as red in my diff image have a 2x2 bounding box, and therefore the calculations differ, ref:

https://github.com/mapbox/pixelmatch/blob/2188ac3faff8ab267236b15ebd1a60f6387cc28d/index.js#L56-L60

**Comment by mourner** [comment]
Yeah, this looks like a bug. Took me some time to notice the red pixels. :) Want to explore a PR for this?

**Comment by IvanSanchez** [comment]
I'm guessing that the premise at the end of the `antialiased()` function...

https://github.com/mapbox/pixelmatch/blob/2188ac3faff8ab267236b15ebd1a60f6387cc28d/index.js#L107-L110

...doesn't hold for pixels at the edges/corners of the image.

**Comment by IvanSanchez** [comment]
> Want to explore a PR for this?

Dunno. I'm not the one who has read all the papers about this :smile:

Maybe the right approach here is to assume that at the edges & corners one a pixel needs to have *more than 1* equal sibling instead of *more than 2* equal siblings.
