### ISSUE TITLE
command line not working 

### ISSUE THREAD

**Issue by VenkateshPS** [mapbox/pixelmatch#56]
Here is what i did 
1. npm install pixelmatch

2. Navigated to local pixelmatch folder after installation.
/Users/XXXX/node_modules/pixelmatch/bin

3. ran  below command on terminal
pixelmatch 1.png 2.png output.png 0.1

Output 
-bash: pixelmatch: command not found

**Comment by tangzhen** [comment]
If you want run pixelmatch as command line tool, you should:
`npm install pixelmatch -g`
or use npx(no need install the pixelmatch)
`npx pixelmatch xxx.png xxx.png`
