### ISSUE TITLE
"No dependencies" but has a dependency

### ISSUE THREAD

**Issue by metaa** [mapbox/pixelmatch#58]
The `README` states that this package does not have any dependencies.
https://github.com/mapbox/pixelmatch/blob/8a5683b7e85760275c94151ebc217522f83793a0/README.md#L16

But there actually *is* a dependency:
https://github.com/mapbox/pixelmatch/blob/8a5683b7e85760275c94151ebc217522f83793a0/package.json#L12-L14

Maybe the phrasing should be updated to something like **`no native dependencies`**?

**Comment by mourner** [comment]
The library itself has no dependencies — you can see that in the source code: https://github.com/mapbox/pixelmatch/blob/master/index.js

The `pngjs` dependency is only used for the `pixelmatch` binary command.
