### ISSUE TITLE
Is there a way to ignore caret on input boxes while comparing two images?

### ISSUE THREAD

**Issue by nkulkarni8** [mapbox/pixelmatch#59]
I have being using the pixel match library for a long time now and it is very helpful in comparing two images and returning diffs. Currently where I am struggling is while comparing two text boxes or input boxes images, since I am entering values at times the baselines or the actual images are giving me caret so the comparison is failing for pixel diffs. Is there any way or plan to ignore the carets on input box images?

**Comment by NiGhTTraX** [comment]
@nkulkarni8 if you have the option of changing the way you take baselines you could include [CSS](https://github.com/NiGhTTraX/react-test-buffet/blob/5873882f487cf56970c01bdecc24ec5a18c240a4/tests/gui/styles.css) that removes the caret from the inputs.

**Comment by nkulkarni8** [comment]
Thanks for your input @NiGhTTraX. I initially thought of changing the css but that is not our usecase, something similar to what module 'looks-same' offers where you can ignore the caret from comparison.

**Comment by mourner** [comment]
Yeah, I think this is the type of thing that should be handled outside of pixelmatch (which only cares about pixel data).
