### ISSUE TITLE
Buffers support regressioin on `5.0.1`

### ISSUE THREAD

**Issue by smhutch** [mapbox/pixelmatch#62]
In `v5.0.1` there appears to be no support for image Buffers.

Given this code: https://cl.ly/4b2774

- On `5.0.1`: I get this error https://cl.ly/a693b1
- On `5.0.0`: things work as expected 👍 

https://github.com/mapbox/pixelmatch/blob/197e8e27eb64f092cd9086b87118b3d0643e6534/index.js#L83-L85

**Comment by mourner** [comment]
What version of Node are you running this on? Can you share a full minimal test case (e.g. as a Gist)? `Buffer` is inherited from `Uint8Array` so this holds true:

![image](https://user-images.githubusercontent.com/25395/59190000-4d47b600-8b84-11e9-999d-5d3f566d8a05.png)

**Comment by mourner** [comment]
Looking at this further, this might be related to this Jest bug https://github.com/facebook/jest/issues/4422
