### ISSUE TITLE
Error when comparing two images with the same sizes

### ISSUE THREAD

**Issue by tonai** [mapbox/pixelmatch#66]
Hello,
here is the code I tested:
```js
import { promises as fs } from 'fs';
import pixelmatch from 'pixelmatch';
import sizeOf from 'buffer-image-size';

const img1 = './public/images/20190605133954-1-atoms.Tables.ATOM-038 - TableCell.png';
const img2 = './public/images/20190605133954-1-atoms.Tables.ATOM-037 - TableHead.png';

const promise1 = fs.readFile(img1);
const promise2 = fs.readFile(img2);

Promise.all([ promise1, promise2 ])
  .then(([ buffer1, buffer2 ]) => {
    const { width: width1, height: height1 } = sizeOf(buffer1);
    const { width: width2, height: height2 } = sizeOf(buffer2);
    if (width1 === width2 && height1 === height2) {
      const diff = pixelmatch(buffer1, buffer2, null, width1, height1, { threshold: 0 });
    }
  })
  .catch(error => console.error(error));
```

And I got the following error:
```
Error: Image sizes do not match.
    at pixelmatch (/home/tocab/Projects/Smile/diplopia/diplopia-api/node_modules/pixelmatch/index.js:19:15)
    at file:///home/tocab/Projects/Smile/diplopia/diplopia-api/test.mjs:17:20
```
I used node v12.4.0 with the `--experimental-modules` flag.

In your lib you are testing `img1.length !== img2.length` and this is false when using Buffers although the images have the same dimensions (800x600).

Here are the two images I used for my test:
![20190605133954-1-atoms Tables ATOM-037 - TableHead](https://user-images.githubusercontent.com/5246045/60969491-edc5fd00-a31f-11e9-87c7-d650c63964c3.png)
![20190605133954-1-atoms Tables ATOM-038 - TableCell](https://user-images.githubusercontent.com/5246045/60969498-f0285700-a31f-11e9-8611-2bee64606e03.png)

**Comment by mourner** [comment]
Pixelmatch accepts raw pixel data (RGBA array) as input. You have to decode the PNG first (e.g. using `pngjs`, like it's done in https://github.com/mapbox/pixelmatch/blob/master/bin/pixelmatch

**Comment by Sabya73** [comment]
Can't compare same images if I do this 
```
router.get("/api/compare/:image1/:image2", auth, (req, res) => {
  s3.getObject({Bucket: config.get("s3.bucket"), Key: req.params.image1}, function(err, data1) {
    s3.getObject({Bucket: config.get("s3.bucket"), Key: req.params.image2}, function(err, data2) {

      const img1 = PNG.sync.read(data1.Body);
      const img2 = PNG.sync.read(data2.Body);
      
      const {width, height} = img1;
      
      if (img2.width !== width || img2.height !== height) {
          console.log(`Image dimensions do not match: ${width}x${height} vs ${img2.width}x${img2.height}`);
          process.exit(65);
      }
      const diff = new PNG({width, height});
      console.log(img1);
      console.log(img2);
      console.log((!isPixelData(img1) ));
      console.log((!isPixelData(img2) ));
      console.log( (diff.data && !isPixelData(diff.data)));
      pixelmatch(img1, img2, diff.data, width, height, {threshold: 0.1});
```

It Throws error as 

> app_1  | {
app_1  |   width: 778,
app_1  |   height: 1334,
app_1  |   depth: 8,
app_1  |   interlace: false,
app_1  |   palette: false,
app_1  |   color: true,
app_1  |   alpha: true,
app_1  |   bpp: 4,
app_1  |   colorType: 6,
app_1  |   data: <Buffer 4e 4d 4e ff 44 42 43 ff 3f 3d 3e ff 3f 3d 3e ff 3e 3d 3e ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3d 3d 3e ff 3d 3d 3f ff 3c 3c 3e ff 3d 3d ... 4151358 more bytes>,
app_1  |   gamma: 0
app_1  | }
app_1  | {
app_1  |   width: 778,
app_1  |   height: 1334,
app_1  |   depth: 8,
app_1  |   interlace: false,
app_1  |   palette: false,
app_1  |   color: true,
app_1  |   alpha: true,
app_1  |   bpp: 4,
app_1  |   colorType: 6,
app_1  |   data: <Buffer 4e 4d 4e ff 44 42 43 ff 3f 3d 3e ff 3f 3d 3e ff 3e 3d 3e ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3d 3d 3e ff 3d 3d 3f ff 3c 3c 3e ff 3d 3d ... 4151358 more bytes>,
app_1  |   gamma: 0
app_1  | }
app_1  | true
app_1  | true
app_1  | false
app_1  | /app/node_modules/aws-sdk/lib/request.js:31
app_1  |             throw err;
app_1  |             ^
app_1  | 
app_1  | Error: Image data: Uint8Array, Uint8ClampedArray or Buffer expected.
app_1  |     at pixelmatch (/app/node_modules/pixelmatch/index.js:17:15)
app_1  |     at Response.<anonymous> (/app/server.js:127:7)
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
app_1  |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
app_1  |     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
app_1  |     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
app_1  |     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9) {
app_1  |   message: 'Image data: Uint8Array, Uint8ClampedArray or Buffer expected.',
app_1  |   code: 'Error',
app_1  |   time: 2020-04-13T21:28:38.997Z

>

**Comment by Sabya73** [comment]
If I do this
`const origin = new PNG().parse(data1.Body);
    const {width, height} = origin;
    console.log(width, height);
    const diff = new PNG({width, height});
    console.log(data1.Body.length );
    console.log(data2.Body.length );
    console.log((data1.Body.length !== data2.Body.length ));
    console.log((data1.Body.length !== data2.Body.length || (diff.data && diff.data.length !== data1.Body.length )));
    console.log((diff.data !== data1.Body.length ) );
    console.log(( diff.data.length !== data1.Body.length ) );
    console.log((diff.data && diff.data.length !== data1.Body.length ) );
    
   pixelmatch(data1.Body, data2.Body, diff.data, width, height, {threshold: 0.1});`

throws error as 

>  /app/node_modules/aws-sdk/lib/request.js:31
> app_1  |             throw err;
> app_1  |             ^
> app_1  | 
> app_1  | Error: Image sizes do not match.
> app_1  |     at pixelmatch (/app/node_modules/pixelmatch/index.js:20:15)
> app_1  |     at Response.<anonymous> (/app/server.js:121:5)
> app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
> app_1  |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
> app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

**Comment by jithinjosejacob** [comment]
https://stackoverflow.com/questions/18510897/how-to-compare-two-images-using-node-js- This works fine,you can try this

**Comment by BlazeGawlik** [comment]
I turned to Jimp: https://www.npmjs.com/package/jimp

const jimage1 = await Jimp.read(imgBuffer);
const jimage2 = await Jimp.read(imgUrl);
const width = jimage1.bitmap.width;
It's effectively a wrapper for pixel-match

**Comment by samuelholland** [comment]
> I turned to Jimp: https://www.npmjs.com/package/jimp
> 
> const jimage1 = await Jimp.read(imgBuffer); const jimage2 = await Jimp.read(imgUrl); const width = jimage1.bitmap.width; var diff = Jimp.diff(jimage1, jimage2, .1); console.log("Percent Difference - ", diff.percent);
> 
> It's effectively a wrapper for pixel-match

This fixed my ongoing issues in a very elegant way! Thank you!

**Comment by nsmithdev** [comment]
Very basic function that only does vertical resize correctly.  But that's all I needed for now 

To do horizonal would need to copy one line at a time plus add the pixels to extend horizonal in the position counter.

```
  const img1 = readImage(controlFolder, imgPath1);
  const img2 = readImage(newCaptureFolder, imgPath1);

  const maxHeight = img1.height > img2.height ? img1.height : img2.height;
  const maxWidth = img1.width > img2.width ? img1.width : img2.width;

  resizeIfNeeded(img1, maxHeight, maxWidth);
  resizeIfNeeded(img2, maxHeight, maxWidth);
```

```
function resizeIfNeeded(img1: any, maxHeight: number, maxWidth: number) {  
  if (img1.height === maxHeight && img1.width === maxWidth) return;

  console.log("Resizeing image");

  const imageCopy = Buffer.alloc(maxHeight * maxWidth * 4);
  img1.data.copy(imageCopy);
  
  img1.height = maxHeight;
  img1.width = maxWidth;
  img1.data = imageCopy;
}
```
