### ISSUE TITLE
image scaling before comparison?

### ISSUE THREAD

**Issue by gaurav517** [mapbox/pixelmatch#67]
Is there any simple way to scale an image before comparison? `resemblejs` gives this option but that library is too heavy. It would be awesome if we can have something like that in `pixelmatch`.

**Comment by mourner** [comment]
Unfortunately not in Pixelmatch, because it operates on raw pixel data, and upscaling isn't a trivial thing to do — there are many algorithms that do it, with different results. I'm going to leave this out of the core.
