### ISSUE TITLE
Finding image match within larger image

### ISSUE THREAD

**Issue by dieterwalckiers** [mapbox/pixelmatch#70]
Hello
I'm working on a function, based on the code in pixelmatch, that finds an image match within a larger image.
Would it be useful to integrate this in pixelmatch? If so I can create a pull request.
If not I'll just create a separate package (with credits to this one of course :) )
thanks
Dieter

**Comment by mourner** [comment]
Hi, I think it would make sense to make it a separate package — I'd like for this one to remain as minimal and simple as possible.

**Comment by dieterwalckiers** [comment]
Yep, fair enough!

**Comment by dieterwalckiers** [comment]
@mourner Just one more question, sorry. Could I create a PR to expose your colorDelta so I can use it in my package? Else I'll have to duplicate the code.

**Comment by mourner** [comment]
@dieterwalckiers sure, let's try that.
