### ISSUE TITLE
Would like to upstream some options: diffMask, drawAA

### ISSUE THREAD

**Issue by zol** [mapbox/pixelmatch#71]
We use pixelmatch at [Chromatic](https://www.chromaticqa.com) and I've been maintaining our own fork with some extra functionality. I'd much prefer to upstream these changes and wanted to feel you out first to see whether you'd be open to merging them. They are backward compatible out of the box and come with tests. I believe they are aligned with pixelmatch's ethos of remaining small, fast and flexible.

The functionality is behind two new options:

- `diffMask` - If `true`, output will be a mask rather than a complete image. `false` by default.
- `drawAA` - If `true`, output will contain `aaColor` pixels for those detected as anti-aliased otherwise they won't be included in the diff output. `true` by default.

I can explain the reasoning behind needing these options in case it's unclear.

**Comment by mourner** [comment]
Hey @zol, this sounds great — PRs welcome! If I understand the context behind these options correctly, would it be simpler to automatically disable drawing AA pixels when `diffMask` is true (so that the mask is different pixels only, which what I'd expect too) instead of adding `drawAA` option?

**Comment by zol** [comment]
Awesome, I'll cook one up without the `drawAA` option as soon as I have a sec.

**Comment by tmeasday** [comment]
@mourner - I've taken over this and created a PR here: https://github.com/mapbox/pixelmatch/pull/73

**Comment by mourner** [comment]
Released as v5.1.0.
