### ISSUE TITLE
Alpha option doesn't seem to be supported

### ISSUE THREAD

**Issue by barryels** [mapbox/pixelmatch#72]
Although the documentation states that:
```
alpha — Blending factor of unchanged pixels in the diff output. Ranges from 0 for pure white to 1 for original brightness. 0.1 by default.
```

Passing an `alpha` value of anything other than the default value of `0.1` doesn't seem to change the diff output.

**Minimal test to recreate the issue:**
Notes:
 - `img1` below is being passed as both the expected and actual image, so there should be no difference between them.
 - The `alpha` option is `0`
```
const fs = require('fs');
const PNG = require('pngjs').PNG,
const pixelmatch = require('pixelmatch');
 
const img1 = PNG.sync.read(fs.readFileSync('test/fixtures/4a.png'));
const {width, height} = img1;
const diff = new PNG({width, height});

pixelmatch(img1.data, img1.data, diff.data, img1.width, img1.height, {threshold: 0.1, alpha: 0});
 
fs.writeFileSync('diff.png', PNG.sync.write(diff));
```

**Expected:**
The `diff.png` image should be completely white

**Actual:**
The `diff.png` image is the expected image with a slight opacity.

**Comment by mourner** [comment]
I can't reproduce this on the fixture you mention — it works as expected. Here's the change from alpha=0.1 to alpha=1:

![image](https://user-images.githubusercontent.com/25395/64130754-0ce78500-cdcd-11e9-9044-3288ff980261.png)

Here's one from alpha=0.1 to alpha=0:
![image](https://user-images.githubusercontent.com/25395/64130780-32748e80-cdcd-11e9-89a8-0e88cc8c739f.png)

**Comment by barryels** [comment]
@mourner Sorry, yeah, I was running off an older version (`4.0.2`) which had a hard-coded alpha value of `0.1`:

[https://github.com/mapbox/pixelmatch/blob/58002be63d062a6efdcad859e705ba7d9a2cefeb/index.js](https://github.com/mapbox/pixelmatch/blob/58002be63d062a6efdcad859e705ba7d9a2cefeb/index.js)

but alpha was added later:
[https://github.com/mapbox/pixelmatch/blob/5ea44fc01ca637bed61adefd1e85e2ac7a75b134/index.js](https://github.com/mapbox/pixelmatch/blob/5ea44fc01ca637bed61adefd1e85e2ac7a75b134/index.js)

Apologies, I must've started working on this before the 5.0.0 change and only recently re-read the docs.
