### ISSUE TITLE
Example of anti-aliasing detection

### ISSUE THREAD

**Issue by brucou** [mapbox/pixelmatch#75]
Congratulations for the great lib. I would like to know if you have an example of usage of the library which features the anti-aliasing algorithm that is  being used. I am thinking of one image, with aliasing and without aliasing, applying the library and finding that the aliased and anti-aliased images are identical. That would be helpful for me for an article that I am writing on the subject. Thanks!

Edit: i am also wondering if this is used by mapbox and for what purposes? I understand that fast is important for mobile. I wonder what is the specific application for maps?

**Comment by mourner** [comment]
The third row in the [examples section](https://github.com/mapbox/pixelmatch#example-output) is a good example of nearly-identical images where one is aliased and other not.

This library is primarily used in [rendering tests](https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration/render-tests) for Mapbox GL.
