### ISSUE TITLE
Support IE11 / other older browsers

### ISSUE THREAD

**Issue by Havunen** [mapbox/pixelmatch#83]
Hey,

We have been using pixelmatch for asserting our image rotation logic and this module seems to work pretty well. However recently we started testing our software using older browsers and noticed pixelmatch shipped code is written in ES6 which fails in JS runtimes where (const, let, etc..) are not supported. 

Are there any plans to ship multiple versions of the code? Maybe there could be different builds in the bin folder using babel or other transpiler? This way default module could still be ES6 like now, but then use alternative pixelmatch.es5.js or something for older browsers. 

Currently we need to include node_modules in our build process to transpile them to get pixelmatch working, it would be way nicer if we could just point to different file in node_modules and exclude node_modules compilation...

What do you think?

**Comment by mourner** [comment]
Doesn't look relevant anymore — the world moved on, and it's still possible to transpile on the user end for those that need it.
