### ISSUE TITLE
Error when comparing two images with the same sizes

### ISSUE THREAD

**Issue by Sabya73** [mapbox/pixelmatch#85]
Can't compare same images if I do this 
```
router.get("/api/compare/:image1/:image2", auth, (req, res) => {
  s3.getObject({Bucket: config.get("s3.bucket"), Key: req.params.image1}, function(err, data1) {
    s3.getObject({Bucket: config.get("s3.bucket"), Key: req.params.image2}, function(err, data2) {

      const img1 = PNG.sync.read(data1.Body);
      const img2 = PNG.sync.read(data2.Body);
      
      const {width, height} = img1;
      
      if (img2.width !== width || img2.height !== height) {
          console.log(`Image dimensions do not match: ${width}x${height} vs ${img2.width}x${img2.height}`);
          process.exit(65);
      }
      const diff = new PNG({width, height});
      console.log(img1);
      console.log(img2);
      console.log((!isPixelData(img1) ));
      console.log((!isPixelData(img2) ));
      console.log( (diff.data && !isPixelData(diff.data)));
      pixelmatch(img1, img2, diff.data, width, height, {threshold: 0.1});
```

It Throws error as 

> app_1  | {
app_1  |   width: 778,
app_1  |   height: 1334,
app_1  |   depth: 8,
app_1  |   interlace: false,
app_1  |   palette: false,
app_1  |   color: true,
app_1  |   alpha: true,
app_1  |   bpp: 4,
app_1  |   colorType: 6,
app_1  |   data: <Buffer 4e 4d 4e ff 44 42 43 ff 3f 3d 3e ff 3f 3d 3e ff 3e 3d 3e ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3d 3d 3e ff 3d 3d 3f ff 3c 3c 3e ff 3d 3d ... 4151358 more bytes>,
app_1  |   gamma: 0
app_1  | }
app_1  | {
app_1  |   width: 778,
app_1  |   height: 1334,
app_1  |   depth: 8,
app_1  |   interlace: false,
app_1  |   palette: false,
app_1  |   color: true,
app_1  |   alpha: true,
app_1  |   bpp: 4,
app_1  |   colorType: 6,
app_1  |   data: <Buffer 4e 4d 4e ff 44 42 43 ff 3f 3d 3e ff 3f 3d 3e ff 3e 3d 3e ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3f 3f 3f ff 3d 3d 3e ff 3d 3d 3f ff 3c 3c 3e ff 3d 3d ... 4151358 more bytes>,
app_1  |   gamma: 0
app_1  | }
app_1  | true
app_1  | true
app_1  | false
app_1  | /app/node_modules/aws-sdk/lib/request.js:31
app_1  |             throw err;
app_1  |             ^
app_1  | 
app_1  | Error: Image data: Uint8Array, Uint8ClampedArray or Buffer expected.
app_1  |     at pixelmatch (/app/node_modules/pixelmatch/index.js:17:15)
app_1  |     at Response.<anonymous> (/app/server.js:127:7)
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
app_1  |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
app_1  |     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
app_1  |     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
app_1  |     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9) {
app_1  |   message: 'Image data: Uint8Array, Uint8ClampedArray or Buffer expected.',
app_1  |   code: 'Error',
app_1  |   time: 2020-04-13T21:28:38.997Z

> 

If I do this
````
const origin = new PNG().parse(data1.Body);
    const {width, height} = origin;
    console.log(width, height);
    const diff = new PNG({width, height});
    console.log(data1.Body.length );
    console.log(data2.Body.length );
    console.log((data1.Body.length !== data2.Body.length ));
    console.log((data1.Body.length !== data2.Body.length || (diff.data && diff.data.length !== data1.Body.length )));
    console.log((diff.data !== data1.Body.length ) );
    console.log(( diff.data.length !== data1.Body.length ) );
    console.log((diff.data && diff.data.length !== data1.Body.length ) );
    
   pixelmatch(data1.Body, data2.Body, diff.data, width, height, {threshold: 0.1});`
```

throws error as 

>  /app/node_modules/aws-sdk/lib/request.js:31
> app_1  |             throw err;
> app_1  |             ^
> app_1  | 
> app_1  | Error: Image sizes do not match.
> app_1  |     at pixelmatch (/app/node_modules/pixelmatch/index.js:20:15)
> app_1  |     at Response.<anonymous> (/app/server.js:121:5)
> app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
> app_1  |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
> app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

**Comment by mourner** [comment]
```js
pixelmatch(img1, img2, diff.data
```

You're passing image objects instead of data. Please check out the readme docs for examples of using this library. https://github.com/mapbox/pixelmatch#nodejs

**Comment by Sabya73** [comment]
If I use this 
`const origin = new PNG().parse(data1.Body);
    const {width, height} = origin;
    console.log(width, height);
    const diff = new PNG({width, height});
    console.log((!isPixelData(data1.data) ));
    console.log((!isPixelData(data2.data) ));
    console.log( (diff.data && !isPixelData(diff.data)));
    console.log(data1.Body.length );
    console.log(data2.Body.length );
    // console.log((data1.data.length !== data2.data.length ));
    // console.log((data1.data.length !== data2.data.length || (diff.data && diff.data.length !== data1.data.length )));
    // console.log((diff.data !== data1.Body.length ) );
    // console.log(( diff.data.length !== data1.Body.length ) );
    // console.log((diff.data && diff.data.length !== data1.Body.length ) );
    
   pixelmatch(data1.data, data2.data, diff.data, width, height, {threshold: 0.1});
    fs.writeFileSync('diff.png', PNG.sync.write(diff));
    });
  });
  });
  
  function isPixelData(arr) {
    // work around instanceof Uint8Array not working properly in some Jest environments
    return ArrayBuffer.isView(arr) && arr.constructor.BYTES_PER_ELEMENT === 1;
`

Get error as

> 
778 1334
app_1  | true
app_1  | true
app_1  | false
app_1  | 377226
app_1  | 1142058
app_1  | /app/node_modules/aws-sdk/lib/request.js:31
app_1  |             throw err;
app_1  |             ^
app_1  | 
app_1  | Error: Image data: Uint8Array, Uint8ClampedArray or Buffer expected.
app_1  |     at pixelmatch (/app/node_modules/pixelmatch/index.js:17:15)
app_1  |     at Response.<anonymous> (/app/server.js:188:4)
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
app_1  |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
app_1  |     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
app_1  |     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
app_1  |     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
app_1  |     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
app_1  |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9) {
app_1  |   message: 'Image data: Uint8Array, Uint8ClampedArray or Buffer expected.',
app_1  |   code: 'Error',
app_1  |   time: 2020-04-16T10:15:21.547Z
app_1  | }

>
