### ISSUE TITLE
ignoreRectangles feature

### ISSUE THREAD

**Issue by curtw** [mapbox/pixelmatch#9]
Proposing to add "ignoreRectagles" feature as in node-resemble-js, where options would support an ignoreRectangles property which is as in resemble:

```
//array of rectangles, each rectangle is defined as (x, y, width, height)
//e.g. [[325, 170, 100, 40]]
```

Pixels within these rectangles would not be tested. Unsure of best way to represent these in diff image.

**Comment by mourner** [comment]
I wonder whether it's worth introducing complexity with features like this, or just leaving this up to the user since it's easy enough to just iterate over and null all pixels in desired areas in both input images.

**Comment by curtw** [comment]
I did a quick implemenation that builds a hash from the rectanges, and then tests the hash with each iteration of the comparison loop:

    function buildIgnoreHash(rectangles) {
        var hash = {};
        for (var i=0; i<rectangles.length; i++) {
            var x1=rectangles[i][0],
                x2=rectangles[i][2]+x1,
                y1=rectangles[i][1],
                y2=rectangles[i][3]+y1;    
                
            for (var y = y1; y < y2; y++) {
                for (var x = x1; x < x2; x++) {
                    hash[x]=hash[x]||{};            
                    hash[x][y]=true;
                }
            }
        }
        return hash;
    }

-

    if (ignoreHash && ignoreHash[x] && ignoreHash[x][y])
        continue;

Surprising to me, it was not any faster than blanking out rectanges in both images.  The only advantage of adding ignoreRectangles feature to the package is that is non-destructive, so you can do something else with the images after comparing them.

**Comment by curtw** [comment]
Another advantage of including this feature in the package is that the color of the ignore rectangles could be set to black in the diff image, making it clear what had been excluded from the comparison.

    if (ignoreHash && ignoreHash[x] && ignoreHash[x][y]) {
        drawPixel(output, pos, 0, 0, 0);
        continue;
    }

Setting the color to black in the input images does not produce a diff image that adequately distinguishes ignore rectangles from darker parts of the input images.

You could black-out the resulting diff image as well, but that's getting a be a lot of extra steps.

**Comment by skyiea** [comment]
Hi.
Any plans to introduce this feature?

**Comment by mourner** [comment]
No plans for now, to keep it simple. There's a workaround:

> it's easy enough to just iterate over and null all pixels in desired areas in both input images

**Comment by adamchenwei** [comment]
@mourner any example code how to do that?

**Comment by mourner** [comment]
A sample snippet of how to clear pixel data in a rectangular region (`x0, y0, x1, y1`):

```js
for (let y = y0; y < y1; y++) {
    for (let x = x0; x < x1; x++) {
        const k = 4 * (width * y + x);
        data[k + 0] = 0;
        data[k + 1] = 0;
        data[k + 2] = 0;
        data[k + 3] = 0;
    }
}
```
