### ISSUE TITLE
Description on NPMJS is misleading

### ISSUE THREAD

**Issue by dmitri-trofimov** [mapbox/pixelmatch#96]
The description states that the library has no dependencies, however it has one that is 600KB+.

**Comment by mourner** [comment]
The dependency is for the `./pixelmatch` binary. The library itself has no dependencies and doesn't need it.

**Comment by dmitri-trofimov** [comment]
Am I missing something? I see this in `package.json`:
![image](https://user-images.githubusercontent.com/46350232/112647270-fee6d280-8e50-11eb-939b-7cefa056d4fc.png)

**Comment by mourner** [comment]
@dmitri-trofimov you are. Please see the comment above.
